spring:
  application:
    name: Sell&Buy
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    show-sql: true
  data:
    redis:
      port: 6379
      host: localhost
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
      region:
        static: ap-northeast-1
server:
  port: 80
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true
    session:
      cookie:
        name: JSESSIONID
        http-only: true
        secure: true
        same-site: strict
      timeout: 30m